package envfile

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestParse(t *testing.T) {
	in := strings.Join([]string{
		"# tcl-lsp environment v1",
		"# tcl 9.0.3 — generated by tools/extract.tcl msgcat",
		"index_file\t/lib/tcl9.0/tm.tcl",
		"index_file\t/lib/tcl9/9.0/msgcat-1.7.1.tm",
		"command\t::msgcat::mc\targs",
		"command\t::fa::c_only_cmd", // C command: name only
		"builtin\t::puts",
		"",
		"garbage line with no tab",
		"unknown_type\t::x", // future record type: skipped, not an error
		"command\t",         // empty name: skipped
	}, "\n")

	env, err := Parse(strings.NewReader(in))
	if err != nil {
		t.Fatalf("Parse error: %v", err)
	}
	if !reflect.DeepEqual(env.IndexFiles, []string{"/lib/tcl9.0/tm.tcl", "/lib/tcl9/9.0/msgcat-1.7.1.tm"}) {
		t.Fatalf("IndexFiles = %#v", env.IndexFiles)
	}
	if !reflect.DeepEqual(env.Commands, []string{"::msgcat::mc", "::fa::c_only_cmd"}) {
		t.Fatalf("Commands = %#v", env.Commands)
	}
	if !reflect.DeepEqual(env.Builtins, []string{"::puts"}) {
		t.Fatalf("Builtins = %#v", env.Builtins)
	}
}

func TestDefaultGlobalPath(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "/xdg")
	if got := DefaultGlobalPath(); got != filepath.Join("/xdg", "tcl-lsp", "environment.env") {
		t.Fatalf("with XDG_CONFIG_HOME: %q", got)
	}
	t.Setenv("XDG_CONFIG_HOME", "")
	got := DefaultGlobalPath()
	if !strings.HasSuffix(got, filepath.Join(".config", "tcl-lsp", "environment.env")) {
		t.Fatalf("fallback should be under ~/.config: %q", got)
	}
}

func TestLoadMissingIsNotAnError(t *testing.T) {
	env, ok, err := Load("/no/such/dir/.tcl-lsp.env")
	if err != nil || ok {
		t.Fatalf("missing file: ok=%v err=%v, want ok=false err=nil", ok, err)
	}
	if len(env.IndexFiles)+len(env.Commands)+len(env.Builtins) != 0 {
		t.Fatalf("missing file should yield empty env: %#v", env)
	}
}

func TestLoadReadsFile(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, ".tcl-lsp.env")
	if err := os.WriteFile(p, []byte("command\t::x::y\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	env, ok, err := Load(p)
	if err != nil || !ok {
		t.Fatalf("Load: ok=%v err=%v", ok, err)
	}
	if !reflect.DeepEqual(env.Commands, []string{"::x::y"}) {
		t.Fatalf("Commands = %#v", env.Commands)
	}
}
