# extract.tcl — introspect a live Tcl environment and emit a tcl-lsp
# environment file (.tcl-lsp.env) that closes the definition-side gaps the
# static index cannot see: commands provided by external packages (including
# runtime-GENERATED procs, which materialize when the package loads) and the
# package source files themselves (indexed for real goto-def targets).
#
# Usage (run with the SAME tclsh/environment your code runs under):
#     tclsh tools/extract.tcl ?package ...?  > .tcl-lsp.env
#
# Output is a line-based artifact (see server/internal/envfile):
#     index_file <abs path>    a .tcl file sourced while loading packages
#     command <name> ?args?    a package-provided command (C or script)
#     builtin <name>           a baseline interpreter command (reserved for
#                              future diagnostics allowlists; ignored today)
#
# NOTE: this EXECUTES package init code (`package require`). Run it
# deliberately, in a trusted dev environment — never automatically.

# ---- helpers ----------------------------------------------------------------

# every command in every namespace, fully qualified
proc all_commands {} {
    set out {}
    set queue {::}
    while {[llength $queue]} {
        set ns [lindex $queue 0]
        set queue [lrange $queue 1 end]
        set pat [expr {$ns eq "::" ? "::*" : "${ns}::*"}]
        foreach c [info commands $pat] { lappend out $c }
        foreach child [namespace children $ns] { lappend queue $child }
    }
    return [lsort -unique $out]
}

# ---- record the baseline (core interpreter, before any package loads) -------

set baseline [all_commands]
foreach c $baseline { set ::isbase($c) 1 }

# ---- trace `source` so we learn exactly which files each package loads ------

set ::sourced {}
rename ::source ::__tcl_lsp_real_source
proc ::source {args} {
    set f [lindex $args end]
    catch { lappend ::sourced [file normalize $f] }
    uplevel 1 [list ::__tcl_lsp_real_source {*}$args]
}

# ---- load the requested packages ---------------------------------------------

foreach pkg $argv {
    if {[catch {package require $pkg} err]} {
        puts stderr "extract.tcl: skipping $pkg: $err"
    }
}

# restore source (politeness; the process exits anyway)
rename ::source {}
rename ::__tcl_lsp_real_source ::source

# ---- emit --------------------------------------------------------------------

puts "# tcl-lsp environment v1"
puts "# tcl [info patchlevel] — generated by tools/extract.tcl [lsort $argv]"

foreach f [lsort -unique $::sourced] {
    # tcl scripts and .tm modules are indexable; skip anything else a package
    # sourced (data files etc.)
    if {[string match *.tcl $f] || [string match *.tm $f]} { puts "index_file\t$f" }
}

foreach c [all_commands] {
    if {[info exists ::isbase($c)]} {
        puts "builtin\t$c"
        continue
    }
    # package-provided: script procs report their real (possibly runtime-
    # generated) signature; C commands are name-only.
    if {![catch {info args $c} arglist]} {
        puts "command\t$c\t$arglist"
    } else {
        puts "command\t$c"
    }
}
